# Generated by Django 5.1.12 on 2025-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0009_add_test_origin_start_time_platform_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="builds",
            name="lab",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tests",
            name="lab",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="builds",
            index=models.Index(fields=["lab"], name="builds_lab"),
        ),
        migrations.AddIndex(
            model_name="tests",
            index=models.Index(fields=["lab"], name="tests_lab"),
        ),
        # Initial population of the columns without needing to update the entire table
        migrations.RunSQL(
            sql="""
                UPDATE builds
                SET lab = misc->>'lab'
                WHERE misc->>'lab' IS NOT NULL
                AND _timestamp >= NOW() - INTERVAL '7 days';
            """,
            reverse_sql="UPDATE builds SET lab = NULL WHERE _timestamp >= NOW() - INTERVAL '7 days';",
        ),
        migrations.RunSQL(
            sql="""
                UPDATE tests
                SET lab = misc->>'runtime'
                WHERE misc->>'runtime' IS NOT NULL
                AND _timestamp >= NOW() - INTERVAL '7 days';
            """,
            reverse_sql="UPDATE tests SET lab = NULL WHERE _timestamp >= NOW() - INTERVAL '7 days';",
        ),
    ]
